### ISSUE TITLE
🙈🙈🙈🙈🙈

### ISSUE THREAD

**Issue by spidunno** [frissyn/Reflux#11]
![🙈🙈🙈🙈](https://ninja.dog/EAQ58l.png "🙈🙈🙈🙈🙈")
![🙈🙈🙈🙈](https://ninja.dog/sduB44.png "🙈🙈🙈🙈🙈")
![🙈🙈🙈🙈](https://user-images.githubusercontent.com/70819261/142932449-88acc0f3-ae88-4d9d-ba34-dab094b75828.png "🙈🙈🙈🙈🙈")

**Comment by frissyn** [comment]
...?

**Comment by ShuchirJ** [comment]
eheh spid it cant do images but #13 >:)
