### ISSUE TITLE
Repl.it python code

### ISSUE THREAD

**Issue by darkdarcool** [frissyn/Reflux#2]
Hi.
So while I was testing out your code in the readme in github, it gave me an error and I had to work around it to get it to work. 
So i think you should change the python code in the readme to this:
``` python
import os
os.system("pip install reflux")
import reflux
t = reflux.Theme({
    "name": "New Theme",
    "author": "Your Username",
    "description": "A simple theme to get started with!",
    "default": "light"
})

t.set_color("primary-1", "whitesmoke")

t.set_colors({
    "primary-2": "rbga(255, 255, 255, 0.48)",
    "primary-3": "hsl(0, 100%, 50%)"
})

t.build("myTheme.min.js")
```
There, if you run that is repl.it it works. 
So I recommend you change the code so it works a little better :)

**Comment by frissyn** [comment]
@darkdarcool 

You're supposed to install the package before running, that's how it works. Either from the package tab on repl.it or through the command line. 

I don't think I need to add that :|

**Comment by darkdarcool** [comment]
You probably don't, but maybe just add the `pip install reflux` somewhere in readme

**Comment by frissyn** [comment]
@darkdarcool OK, just put a nice looking installation guide in the README, thanks.

**Comment by darkdarcool** [comment]
Alright thanks, looks super good!
