### ISSUE TITLE
Joint projects

### ISSUE THREAD

**Issue by BD103** [frissyn/Reflux#8]
Hello! After I never followed up on #5, I felt kind of bad. This project was really interesting for me, but I couldn't figure out a way to generate the CSS in a pythonic manner. Beyond that, the project seemed dead so I wasn't sure if it would be worth it.

While figuring this all out, I learned a lot about how bookmarklets worked and Replit's design system. 2 days ago, I was determined to share this knowledge. There weren't any good Python tools for this process, so I instead created [a framework](https://github.com/BD103/Custom-Replit-Theme) for developing the styling with Sass. I also wanted some general guides and references for people who also wanted to create these designs.

Thus I created [Replit Theming](https://bd103.github.io/Replit-Theming/), a website hosting a collection of resources for Replit UI design. This would have a step-by-step guide to theme design, how I create themes, and maybe a few examples.

However, I realized yesterday that you picked up the project again.

...

Yeah, I created the Sass project thinking that it would be an alternative to Reflux that was easier and more extensible. (I don't mean to be rude, but the API for [0.2.0](https://pypi.org/project/reflux/0.2.0/) wasn't the most pythonic or easy to use.) Anyways, I now have a predicament. Do I drop the project or do I continue it on? Reflux is back in action, so being the alternative wouldn't work.

My decision was to put more effort into the website since that would still be helpful. This was my plan until a few hours ago, where I thought: What if we worked together on all three?

We create a Github org where these three projects can live together in harmony. You can contribute to the website if you want, and I possibly can suggest some features and bug fixes.

I completely understand if you don't want to do this, I just feel like the projects are too similar to be kept apart.

Thank you,

-BD103

**Comment by frissyn** [comment]
Oh thanks so much for your interest in contributing, what you've done so far great! I don't really have any plans to make a GitHub Org for Reflux, or open the project to multiple maintainers (the most I have is a Replit team for the nice URL) but I'd be more than happy to link your website in the docs once it's in a good place. I did look at it the other day and it's honestly a great resource.

Thanks!

**Comment by frissyn** [comment]
If it's of any interest, the next major step is to create a browser extension for Reflux, since bookmarklets are tedious and annoying. Bookmarklets are the current focus of Reflux because a good portion of Replit's users (and me) use it a lot in a school environment, where extensions and Web Inspect are blocked, so bookmarklets are the only option.

**Comment by BD103** [comment]
Got it. I know I little bit about Chrome extensions, so I'll start there.

**Comment by BD103** [comment]
I realize that there are a ton of Chrome extensions that already exist, so maybe you should just make a guide on using one of those.

**Comment by ShuchirJ** [comment]
Hi there! I'm Snow, another collaborator on this project.
All chrome extensions already out there are css injectors, where you give it specific css code to inject (...hence the name). That isn't very user friendly, so we plan to make our own extension where we let the user specify colors, and do the rest for them! I'm not sure if frissyn has planned this or not, but we might also integrate our marketplace (currently a WIP),  where users can share their theme with others and explore other themes.

**Comment by BD103** [comment]
Interesting. I don't know enough about the marketplace and API to do that kind of thing. This probably is something only you or Frissyn could do.

**Comment by frissyn** [comment]
I do plan on making custom extension, I just haven't found any time because I've been swamped with schoolwork and other obligations. Hopefully I can get something up soon.
